Feature/napsspo 346:   tssc-tool-image-scanner
rhtconsulting/tssc-containers pull request #19
Opened 2020-09-03 14:23 UTC by jbride

tssc-tool-image-scanner

Builds on tssc-tool-buildah image and adds scap packages

2020-09-03 19:16 UTC, kharyam requested changes
Looks good, couple of changes

2020-09-03 19:16 UTC, kharyam commented on README.md
> +
Can we had a similar comment as with buildah in the README:

```
> **_NOTE:_** This image is not automatically built by GitHub actions because it requires to be built on a subscribed RHEL 8 machine recently.
```

We'll need a backlog Jira issue to fix this image and the buildah image so they can run unprivileged and be built outside of a rhel 8 box

2020-09-03 19:16 UTC, kharyam commented on README.md
> +## tssc-image-scanner
Probably want to update the name of this image / subfolder to be `tssc-tool-openscap` to call out the specific tool that is supported. We'll potentially have other image scanners in the future.

2020-09-09 11:41 UTC, kharyam approved these changes

2020-09-11 18:47 UTC, HunterGerlach commented on tssc-tool-openscap/Dockerfile.ubi8
> +# CMD [ "/usr/bin/oscap-chroot" ]
nit: should be removed since unused

2020-09-11 19:03 UTC, HunterGerlach approved these changes

2020-09-11 19:04 UTC, merged