NAPSSPO-1024 - tssc-containers - tssc user doesn't actually exist, causes issues for rootless buildah
rhtconsulting/tssc-containers pull request #26
Opened 2020-09-23 15:34 UTC by itewk

#### What is this PR About?
* tssc-base update to actually create tssc user
* tssc-base add args:
  - ARG TSSC_USER_NAME=tssc
  - ARG TSSC_USER_UID=1001
  - ARG TSSC_USER_GID=0
  - ARG TSSC_HOME_DIR=/home/tssc
* update all images to use TSSC_USER_UID
* remove depricated 'MAINTAINER" line from all Dockerfiles
* tssc-tool-maven - remove settings.xml

Related:
* NAPSSPO-1025 - tssc-jenkins-library - openscap container is running as privilaged
* NAPSSPO-1018 - tssc-jenkins-library - buildah container is running as privilaged

2020-09-23 19:14 UTC, kharyam requested changes
Minor typo

2020-09-23 19:14 UTC, kharyam commented on tssc-base/Dockerfile.ubi8
> +RUN useradd tssc --uid $TSSC_USER_UID --gid $TSSC_USER_GID --home-dir ${TSSC_HOME_DIR} --create-home --shell /sbin/noloing && \
`/sbin/noloing` -> `/sbin/nologin`

2020-09-23 19:16 UTC, itewk commented on tssc-base/Dockerfile.ubi8
> +RUN useradd tssc --uid $TSSC_USER_UID --gid $TSSC_USER_GID --home-dir ${TSSC_HOME_DIR} --create-home --shell /sbin/noloing && \
fixed.

2020-09-23 21:16 UTC, kharyam approved these changes
Looks good

2020-09-24 13:44 UTC, kfrankli approved these changes
Really like the switch to human language for logs

2020-09-24 13:44 UTC, kfrankli commented on .github/workflows/publish.yaml
> +          echo "Verify java installed"
Huh, I like this human language a lot more!

2020-09-24 13:44 UTC, merged

2020-09-24 14:06 UTC, itewk commented on .github/workflows/publish.yaml
> +          echo "Verify java installed"
glad to hear it :)

I didn't update all of them. but someone else can do that :).

2020-09-24 14:29 UTC, itewk commented
auto publish of images: https://github.com/rhtconsulting/tssc-containers/actions/runs/270736709
manual push images:
```
14:26 $ ./manual-publish.sh edge tssc quay.io

--------------------

LOGIN: quay.io
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to quay.io

--------------------

CALCULATE TAGS

--------------------

CONFIRMATION
    IMAGES: tssc-tool-buildah tssc-tool-openscap
    IMAGE VERSION: edge
    IMAGE TAGS: edge sha-ef35f8e3
    REGISTRY REPOSITORY: tssc
    REGISTRY_URI: quay.io

Are you sure you want to build, tag, and push? (Y/N): Y
```